# 端口号
server:
  port: 8222
  servlet:
    context-path: /dispatchsys
# 服务名
spring:
  application:
    name: service-gateway
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        # server-addr: 127.0.0.1:8848 192.168.1.3:28999
        server-addr: 192.168.1.3:28999
    # 使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      # 配置路由规则
      routes:
        - id: service-acl
          # 设置路由uri  lb://注册服务名称
          uri: lb://service-acl
          # 具体路径规则
          predicates:
            - Path=/dispatchsys/*/acl/**
          filters:
            - StripPrefix=1
