# 服务端口
server:
  port: 8223

# 服务名
spring:
  application:
    name: service-acl

  # mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/acldb?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    url: ENC(JCpxCkq4eCfdBYBHDKPim/Va/8K8r0S75hsvk0GgjZH5Hto29GvxU8XyRMjTwiKddaGIGtFWmMhQU5uiZOQribDY1J4ZT/fmAaFUToPBUs5yc0souhVIq2A9ALvClFr94DEwNbw2+B5vO2VnGW2ld39IRRfRanw86A0xb22ppxn8WMhMAVIekJPiTad29zHHbL6FrHishGtcI/1xDIYPlQ==)
    username: ENC(MjTm0lO4+IFaHxrln39TOQ==)
    # localhost Mysql_123456
    password: ENC(4Q7edDWexFbWCFE+leDwmkbJ6bE/OiySMplLKADlszQ=)

  # redis连接
  redis:
    # host: 127.0.0.1  port: 6379       host: 192.168.1.3  port: 9736
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        # 最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        # 最小空闲
        min-idle: 0

  # nacos服务地址
  cloud:
    nacos:
      discovery:
        # server-addr: 127.0.0.1:8848 192.168.1.3:28999
        server-addr: 127.0.0.1:8848

  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


# 配置mapper xml文件的路径
mybatis-plus:
  mapper-locations: classpath:com/atguigu/aclservice/mapper/xml/*.xml
  configuration:
    # mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# bpmn上传后预览映射路径： linux: file:/root/Activiti/
bpmn-path-mapping: D:\\WangJianIDEA_Test\\activiti-imooc\\src\\main\\resources\\resources\\bpmn\\

camunda:
  bpm:
    database:
      schema-update: true

# jasypt加密的密匙
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: PNG5egJcwiBrd+chupacabras=
